name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg   # use a non-GUI backend for matplotlib
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint (flake8)
        run: |
          flake8

      - name: Run tests (pytest)
        run: |
          pytest -q

      - name: Smoke run the script
        run: |
          python Consumer_Behavior.py


